### ISSUE TITLE
Update debugging statements to be compiler flag dependent. 

### ISSUE THREAD

**Issue by jklasdfj** [490G20/QUENOS#18]
As demonstrated by the supervisor 

Add debug compiler flag -DDEBUG to the end in the altera monitor settings, update the code as follows below

Then wrap the relevant print statements 
# ifdef DEBUG
// code to be run only when select debug flag is present
#endif”

ask @jharon for details as his account had the code

**Comment by usernameisntallowed** [comment]
reviewed in person with group, merging
